[package]
name = "rustreams"
version = "0.1.0"
authors = ["David Sauer <davedamoon@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rdkafka = { git = "https://github.com/fede1024/rust-rdkafka", branch = "master" }
maplit = "1.0.2"
rand = "0.3.15"
tokio = { version = "1.0.2", features = ["full"] }
env_logger = "0.8.2"
log = "0.4.13"
futures = "0.3.12"
