version: '3.7'

services:

  zookeeper:
    image: bitnami/zookeeper:3.6.2-debian-10-r156
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:2.7.0-debian-10-r65
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  postgres:
    image: postgres:13.2-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password123
